version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg_go_blog
    restart: always
    environment:
      POSTGRES_DB: go_blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
